    # Generated by Django 5.2.6 on 2025-10-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Descrição')),
                ('data_add', models.DateField(auto_now=True, verbose_name='Data de criação')),
                ('done', models.BooleanField(default=False, verbose_name='Feita')),
            ],
        ),
    ]
